apiVersion: apps/v1
kind: Deployment
metadata:
  name: intrusion-detection-deployment
  labels: 
    app: fastapi-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
      - name: fastapi-server
        image: detect_server:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8891
        # resources:
        #   limits:
        #     cpu: "500m"
        #     memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: intrusion-detection-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-server
  ports:
  - protocol: TCP
    port: 8891
    targetPort: 8891
    nodePort: 30000



